### ISSUE TITLE
GRPC Server not processing request

### ISSUE THREAD

**Issue by abhilashra** [tsloughter/grpcbox#106]
Hi @tsloughter ,

I am working on usage of grpcbox. i followed the implementation as mentioned. i am using unary request. and I am trying to fire the client calls using grpcurl.

But i see the first request is succesful and second request throws the below response.

`/grpcurl -v -plaintext -d '{"msg": "1"}' -import-path /home/aaaa/route/myapp/proto --proto dp_api.proto localhost:10001 dp.Route/Ping

Resolved method descriptor:
rpc Ping ( .dp.PingMsg ) returns ( .dp.PongMsg );

Request metadata to send:
(empty)

Response headers received:
content-type: application/grpc+proto
user-agent: grpc-erlang/0.1.0

Response trailers received:
(empty)
Sent 1 request and received 0 responses
ERROR:
  Code: Internal
  Message: stream terminated by RST_STREAM with error code: STREAM_CLOSED
`

Can u get some information, how to fix this. I am using Unary Operator

**Comment by tsloughter** [comment]
Was this resolved?
