### ISSUE TITLE
Does it support long-lived streams (like for push notifications or pub/sub)? 

### ISSUE THREAD

**Issue by abogosyan** [tsloughter/grpcbox#19]
I mean, something like this: https://github.com/itisbsg/grpc-push-notif

Client opens stream rpc on server which is never ends. 
Doc for list_feature function says "The stream is ended by the server when the function completes"

**Comment by tsloughter** [comment]
Yes, just don't end it. Look in the interop example, there is a "chat" bidi stream that never ends.

**Comment by abogosyan** [comment]
Thank you, it works.
But I have another "issue": i have simple client and service and trying to make unary RPC call from shell:
5>test_client:hello(#{hello_request_body => <<"lalala">>}).

answer is successful:
{ok,#{hello_reply_body => <<"hello reply from test">>},
    #{headers =>
          #{<<":status">> => <<"200">>,
            <<"user-agent">> => <<"grpc-erlang/0.1.0">>},
      trailers => #{}}}

but calling process have unconsumed message in mailbox after that:
6> flush().                                                                                           
Shell got {'END_STREAM',3}

**Comment by tsloughter** [comment]
Yea, sorry, that will change but I haven't had time to rework the client like it needs to be.

Hm, there might be a quicker fix for this particular problem though... looks like it simply needs to include a receive on `END_STREAM` after it receives `{eos, StreamId}` in `grpcbox_client (line 198).

The longer term plan is to not be sending any messages to the process that makes the request, that was a bad idea done for expediency and under the assumption it could be wrapped later. But I instead plan to get rid of that altogether instead of wrapping it.

**Comment by abogosyan** [comment]
> The longer term plan is to not be sending any messages to the process that makes the request, that was a bad idea done for expediency and under the assumption it could be wrapped later. But I instead plan to get rid of that altogether instead of wrapping it.

Will it change for "streaming" requests? Now it looks very convenient to have "output stream RPC" from some gen_server and  then just collect messages via handle_info without need for grpcbox_client:recv_data calls

**Comment by tsloughter** [comment]
Can definitely still allow that to work as is so you can receive them in handle_info.

**Comment by abogosyan** [comment]
Hello, looks like grpcbox_channel now starting as registered process and needs to have atom() name. That makes it hard to add channels dynamically (I mean one channel with one endpoint per session, when you need to connect to specific endpoint explicitly). That could be fixed two ways:
- allow add Endpoints dynamically and use gproc_pool 'direct' strategy to select specific (added) endpoint by position, but it looks clunky
- another option is to allow use any term for channel name, using "register via gproc" and just spawn new "channel + endpoint(subchannel)" pair using grpcbox_channel_sup:start_child

Also i found that there is a small gap between channel start and actual workers subchannels start, so you can't make RPC call immedialtely after grpcbox_channel_sup:start_child because worker can be not registered yet and you will crash in grpcbox_subchannels:conn(Pid) function because Pid will be undefined. That happens because grpcbox_channel statem is starting in 'idle' state and use 'connect' event to start actual workers and proceed to 'connected' state, but 'pick' doesn't use gen_statem:call to check that. I think that workers could be started directly in grpcbox_channel:init function so after channel started it will have ready workers to process requests. BTW it's unclear why we need idle state in channel at all as it's just "balancer" for actual workers. Another option is to process 'pick' logic via gen_statem:call (as it was intended i think). 

I can make a PR as soon as you have no objections

**Comment by abogosyan** [comment]
Opened PR here: https://github.com/tsloughter/grpcbox/pull/20
