### ISSUE TITLE
Opening and closing client channels (gRPC conncetions)

### ISSUE THREAD

**Issue by drasko** [tsloughter/grpcbox#22]
Currently client channels (gRPC conncetions) can be definied only in the configuration before starting of the application.

It would be good to be capable to dynamically open and close gRPC connection while keeping the connection handle as a reference in our application state - this is how many client drivers are working.

Typically, in my application I handle [gRPC comm from within gen_server](https://github.com/mainflux/mainflux/blob/master/mqtt/verne/src/mfx_grpc.erl), and then opening and closing gRPC connection on each gen_server's `init/1` and `terminate/2`.

Apart from this - if this dynamic connect/disconnect can not be added - what is the best way today do do the actual channel termination? It is cler how chonnels are created (by initial config prior to starting the app), but what is the best way to close channels that we do not use later in the application?

**Comment by abogosyan** [comment]
You can add channels dynamically via grpcbox_channel_sup:start_child, and then stop the channel using grpcbox_channel:stop... And btw, channels are not equal connections in grpc

**Comment by tsloughter** [comment]
You can setup a channel with https://github.com/tsloughter/grpcbox/blob/master/src/grpcbox.erl#L36

**Comment by tsloughter** [comment]
Or what @abogosyan said.

**Comment by tsloughter** [comment]
And yea, the client side load balancing "needed" by grpc makes the channel a higher level abstraction that you likely wouldn't track like a connection, though possible. It might be useful to use a connection directly when building basically your own channel/subchannel layer, but for typical usage it is better to use a channel.

**Comment by drasko** [comment]
@abogosyan I tried that and that will not work, because when I try to send over the channel created like that it is reported as `unknown` - because it is not put into `Opts` (and client send function is trying to fetch channel name from Opts).

**Comment by abogosyan** [comment]
Yeah, you should put channel name in generated client methods Options argument (all generated methods have that variant) like #{channel => my_challen_name}, because generated client use default_channel by default

**Comment by drasko** [comment]
@abogosyan I am passing channel name as a caller, wanted to select a certain channel - but `grpcbox` does not have it in internal application options - as they were never set because we called `grpcbox_channel_sup:start_child()` directly.

**Comment by drasko** [comment]
@tsloughter I do not understand how [this one](https://github.com/tsloughter/grpcbox/blob/master/src/grpcbox.erl#L36) is really used. And I do not need server, only client.

**Comment by tsloughter** [comment]
@drasko yea, that was my bad, not what you wanted. @abogosyan is right.

Do you have a crash you can share? It sounds like you are saying something isn't set properly when you create with `grpcbox_channel_sup:start_child`?

**Comment by abogosyan** [comment]
@drasko please look how channel application settings are applied here: https://github.com/tsloughter/grpcbox/blob/d279374d0a4d716bb74cced023581e05daef3332/src/grpcbox_app.erl#L14, you can definitely do the same manually at any point in your own application like I wrote before

**Comment by drasko** [comment]
@tsloughter @abogosyan let me try to do it and I'll report here if it works, or logs from problems.

**Comment by drasko** [comment]
OK, tried `grpcbox_channel_sup:start_child()` approach and it works reliably.

Thanks @abogosyan and @tsloughter, closing this issue.
