### ISSUE TITLE
Channels leak memory

### ISSUE THREAD

**Issue by KennethL** [tsloughter/grpcbox#35]
gprcbox version is v0.11.0
The grpcbox library leaks memory for each message sent on an open channel. Closed streams accumulate in the data of gen_statem for the h2_connection of chatterbox:

```
{connected,{connection,client,[],undefined,
                       {gen_tcp,#Port<0.256>},
                       {settings,...}
                       {settings,...}
                       260494386,97150,
                       {hpack_context,...}
                       {hpack_context,...}
                       {[],[]},
                       12649,
                       {stream_set,client,
                                   {peer_subset,unlimited,1,0,12649,
                                                [{active_stream,1,...}
                                                 {closed_stream,3,...}
                                                 {closed_stream,5,...}
                                                 {closed_stream,7,...}
                                                 {closed_stream,9,...}
                                                 {closed_stream,11,...}
                                                 ...}

```
The `h2_connection:get_response()` function provides a way of marking closed streams as garbage in order to free them but this is not used by grpcbox. Grpcbox reads response data directly as it is streamed in, not in the end as one piece. Because of this grpcbox never calls `h2_connection:get_response()` and the memory is not freed. Under load the memory grows quickly and as the growing data structure is accessed repeatedly, also the CPU usage increases rapidly.

**Comment by tsloughter** [comment]
Thanks for the detailed report! This is the grpcbox client, right? If so the client has continued to be something I wrote quickly, needing only the server for work, but have a partial rewrite almost ready. There is also a PR and some ideas for improving chatterbox's handling of many streams.

I had some time to work on grpcbox last week and hope to do so again this week. The client is important now because of its use by the OpenTelemetry exporter, so I need to improve its quality :)

I'll check whether I can easily patch the current client for this issue or my rewrite (and get it out in a timely manner) today.

**Comment by tsloughter** [comment]
Added a test https://github.com/tsloughter/grpcbox/pull/38 and should have a fix tomorrow. It will require another patch to chatterbox.

**Comment by psalin** [comment]
Hi @tsloughter and thanks for a quick response. I work with @KennethL and I see you have already added a fix on the chatterbox side. We've been running grpcbox under some load and found these leaks. We will also write issues for some other things we find.

**Comment by tsloughter** [comment]
@psalin great, thanks!

Curious, have you been using the server as well? I hope it is far more stable, but some of these issues may cross server and client.

**Comment by psalin** [comment]
Yes, the stream leak issue was found on the server side, but it has been running stably.
