### ISSUE TITLE
The connection can break on concurrent unary requests

### ISSUE THREAD

**Issue by psalin** [tsloughter/grpcbox#39]
When running concurrent unary requests, HTTP/2 HEADERS frames are sometimes sent in an order where a lower stream identifier is sent after an already sent higher one. This causes a HTTP/2 connection error and breaks communication when it happens.

**Comment by psalin** [comment]
It is actually this issue in chatterbox: https://github.com/joedevivo/chatterbox/issues/136. An allocated stream identifier is not guaranteed to be sent out before the next one.

**Comment by tsloughter** [comment]
Do you have a test case for this? Should it "work" to test by just spawning a couple processes making unary requests on the same connection over and over until it blows up? Is it fairly consistent at blowing up or is it timing based?

**Comment by psalin** [comment]
It is timing based and probably depends on where it is run but at least for me spawning 100 processes that send a unary request reproduces it consistently.
