### ISSUE TITLE
The connect timeout for a channel is infinite

### ISSUE THREAD

**Issue by psalin** [tsloughter/grpcbox#43]
In chatterbox, h2_connection:init does not set a timeout for connect() so in case there is no IP level response, it will take a long time before a unary request returns when the channel is in disconnected state.

A workaround of changing connect/3 to connect/4, specifying a hardcoded timeout does fix this. However, in both the fixed and unfixed situation a crash report is generated by the h2_connection gen_statem process exiting so it is not very graceful as is.

In general, being able to to control connect and read timeouts through options would be a nice addition, currently at least on the chatterbox side timeouts seem hardcoded.

**Comment by tsloughter** [comment]
Yea, I can add a configurable timeout that is passed to a new chatterbox function, and maybe should have a default of like 5 seconds.

I always forget the rules for crash reports.. I think the connection process just needs to stop with `normal` or `shutdown` reason
