### ISSUE TITLE
No client stream callback for stream termination

### ISSUE THREAD

**Issue by psalin** [tsloughter/grpcbox#72]
If a stream terminates unexpectedly without END_STREAM, grpcbox does not learn about this and will leave the stream hanging without sending eos. For example if the h2_connection closes down due to socket errors, the grpcbox stream will not notice it.

**Comment by tsloughter** [comment]
Thanks for these. Will get to them soon.

**Comment by psalin** [comment]
I noticed that I failed to add the new callback to all test files for the chatterbox PR so the tests fail for it. I will try to find time to update the PR to fix that soon. Would also like to add a test for this situation to chatterbox.
