### ISSUE TITLE
Generate `_pb.erl` files does not escape builtin type such as `node`

### ISSUE THREAD

**Issue by alissa-tung** [tsloughter/grpcbox#77]
An example would be like:

```protobuf
message Node {}
```

**Comment by tsloughter** [comment]
I vaguely recall this being an issue. Is the issue just with the type spec? Those can be disabled with `{type_specs,false}` option to gpb.

**Comment by alissa-tung** [comment]
> I vaguely recall this being an issue. Is the issue just with the type spec? Those can be disabled with `{type_specs,false}` option to gpb.

Thx!
