### ISSUE TITLE
Using it with `rebar3 new release`

### ISSUE THREAD

**Issue by Fabs** [tsloughter/grpcbox#8]
I am trying to configure grpcbox with a rebar3 release. I cannot get the files to be generated at `apps/models/src`.

My configuration looks like.
```
{grpc, [{protos, "protos"},
        {out_dir, "apps/models/src"},
        {gpb_opts, [{o, "apps/models/src"},                
                    {out_dir, "apps/models/src"},
                    {module_name_suffix, "_pb"}
                   ]
        }]
}.
```

**Comment by tsloughter** [comment]
Argh, I fixed this and looks like I never pushed it and lost it the changes because I wiped that old work laptop! :)

I'll get this fixed again and actually pushed to the plugin hopefully soon, definitely by early next week. It isn't that much to change but I remember it being a little confusing when I did it last.

**Comment by tsloughter** [comment]
Hm, no, weird, it seems to work on the project I remember having the issue with and I thought I had had to make changes.

Are you using the latest github master of the plugin or the hex package?

**Comment by tsloughter** [comment]
And what should work is:

```
{grpc, [{protos, "protos"},
        {out_dir, "apps/models/src"},
        {gpb_opts, [{o, "apps/models/src"},                
                    {module_name_suffix, "_pb"}
                   ]
        }]
}.
```

Been thinking it should use `out_dir` from grpc options for `o` in `gpb_opts` unless another one is specified though. I'm going to make that change, but it should still work as is.

**Comment by tsloughter** [comment]
@Fabs were you able to get this working with my example?

**Comment by Fabs** [comment]
Oh, thanks for the follow up. I moved on from this project, and the company shortly after this. I am sorry I can't really verify your fix. Thanks for looking into it though.

**Comment by tsloughter** [comment]
Ok, I'll close this for now then. Thanks.
