### ISSUE TITLE
grpc-timeout header not matching the spec

### ISSUE THREAD

**Issue by tonnyk00** [tsloughter/grpcbox#85]
Hi,

When testing with a deadline in context, the timeout value is converted to nanosecond in grpc-timeout header.
But there is no check of the TimeoutValue range, which could result in the server rejecting the msg with protocol error.

The [grpc spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) specified that the TimeoutValue can contain at most 8 digits:

> TimeoutValue → {positive integer as ASCII string of at most 8 digits}

Best regards,
Tonny

**Comment by tsloughter** [comment]
Ah thanks!
