### ISSUE TITLE
Client hangs forever on the first call if endpoint is unreachable

### ISSUE THREAD

**Issue by eldarko** [tsloughter/grpcbox#9]
While making the first request the `grpcbox_client_stream` tries to obtain HTTP2 connection object with `grpcbox_subchannel:conn/1`.

Calling `grpcbox_subchannel:conn/1` (being in `idle` state at first) causes `grpcbox_subchannel` to connect. But if `h2_client:start_link` fails, - for example, because the endpoint is not up now, - the state of `grpcbox_subchannel` remains unchanged (i.e. `idle`) in a little bit inconsistent state. It neither crashes nor  attempts to re-connect.

I see that an `idle_timeout` attribute is introduced to the state, so I guess the intention was to do something after some period of time, but the attribute is not used.

Further observations:
The `h2_client:start_link` creates a link with `grpcbox_subchannel` so if the connection is successful at the initial connect, but closed further, the `grpcbox_subchannel` is expected to exit as well. BUT the `process_flag(trap_exit)` is set to `true`. That means that in `ready` state the statem receives {'EXIT',...} event which will be skipped by 

> handle_event(_, _, _) ->
>    keep_state_and_data.

and again the statem remains in `ready` state, but neither crashes nor attempts to re-connect.

Did I miss something?

How did you expected to handle problems with h2_connection?

This is a design decision so I find it better to discuss the issue before submitting the PR.

**Comment by tsloughter** [comment]
@eldarko hey, sorry I missed this issue being opened. I'll take a look tomorrow morning.

**Comment by tsloughter** [comment]
Ah, but I can say it looks like you are right about needing subchannel to handle EXIT. Not sure I ever finished all I wanted to do with subchannel. But I will need to soon because planning to use the client for building a reporter for https://github.com/census-instrumentation/opencensus-erlang which will be used in production.

Open to any ideas you have and PRs.

**Comment by tsloughter** [comment]
@eldarko I pushed a fix for this issue along with a test to the test suite. I want to change the api but it will at least now crash, because `grpcbox_subchannel:conn` will return `{error, econnrefused}`, instead of waiting to `infinity` if it can't get a connection.
