### ISSUE TITLE
-spec incorrect for enum generated erlang code

### ISSUE THREAD

**Issue by geib** [tsloughter/grpcbox#93]
I have a .proto file with enum definitions, and when I generate the erlang code I find that the -spec definitions for fqbin_to_msg_name() and msg_name_to_fqbin() are swapped, see below snippet.

```erlang
-spec msg_name_to_fqbin(_) -> no_return().
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


-spec fqbin_to_msg_name(_) -> no_return().
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).
```

**Comment by tsloughter** [comment]
Thanks but this is an issue with the proto generator gpb, https://github.com/tomas-abrahamsson/gpb, that is used to generate the protobuf encode/decode module.

**Comment by geib** [comment]
Understood. Thanks.
